Feature RustyBlue detections-detection
YamatoSecurity/RustyBlue pull request #19
Opened 2021-04-19 17:08 UTC by 7itoh

## detection.rsの作成
　課題点があり、実装方法を相談したいです。

## 課題
　[E0382] borrow of moved value: `event_id`. 
　[Note] value borrowed here after move

　copy trait に関するErrorを、event_idで検知しています。
　→手法に悩んでおり、コードレビューにより確認をさせてください。

2021-04-20 05:50 UTC, nishikawaakira commented
@7itoh 
matchの前にdetectionを呼んでしまったら意味が無いので、
matchの後でdetection関数を呼ぶようにして、match event_id.as_str() にするだけでコンパイルエラーはなくなると思います。

エラーの内容自体は参照渡しについて勉強されると良いかと思いますー

2021-04-20 05:54 UTC, nishikawaakira commented
というかmatchしたときにdetectionをコールするというのが正しいですね

2021-04-20 13:33 UTC, 7itoh commented on src/detections/detection.rs
> -                                match &*event_id {
55 - 65 行までの処理へ変更をしました。
event_id マッチの処理へ、Secutity/System ~~ Applockerまで適用しています。

2021-04-20 13:34 UTC, 7itoh commented on src/detections/detection.rs
>                                  //&other.detection();
else処理に関して、コメントチェックを外すのみでよいのかを質問させてください。

2021-04-20 14:24 UTC, 7itoh commented on src/detections/detection.rs
>                                  }
55 - 65 行までの処理へ変更をしました。

■変更の対象
　Secutity/System ~~ Applockerまで適用しています。

2021-04-22 18:28 UTC, nishikawaakira reviewed
プルリクを出すのはコーディングが終わった後でお願いします。
相談レベルであれば、ブランチをpushしてissueにコメントを残してもらえれば誰でも確認できるのとslackに通知がいきますので。また、この件 #18 がissueですので、次回からはissue番号をブランチ名に含むようによろしくお願いします。今回は大丈夫です。

2021-04-29 14:26 UTC, hitenkoku requested changes
@7itoh レビューを実施いたしました。ご確認いただき、完了したら私にメンションをしていただければ確認致しますのでよろしくお願いいたします。

2021-04-29 14:26 UTC, hitenkoku commented on src/detections/detection.rs
>                                  }
コメントで対象個所の身に記載をしてしまうとL55-65で「変更の対象」の適用がなされていると誤認してしまうので、今後、ソースコードを対象としたレビューではご注意いただければと思います。

2021-04-29 14:26 UTC, hitenkoku commented on src/detections/detection.rs
> +                                    "4688" | "4672" | "4720" | "4728" | "4732" | "4756"
channelの指定がSystemとなっているが指定しているeventIDがSecurityになっています。
L68-69の条件を以下のように変更していただくと正しいと思いますがいかがでしょうか。

```suggestion
                                    "7030" | "7036" | "7045" | "7040" | "104"
```

2021-04-29 14:26 UTC, hitenkoku commented on src/detections/detection.rs
> +                                    "7030" | "7036" | "7045" | "7040" | "104" => {
channelはL54でSecurityとなっていますが、マッチさせているeventIDがSystemのものになっています
L56の条件を以下のように変更していただくと正しいと思いますがいかがでしょうか。
```suggestion
                                    "4688" | "4672" | "4720" | "4728" | "4732" | "4756" | "4625" | "4673" | "4674" | "4648" | "1102" => {
```

2021-04-29 14:26 UTC, hitenkoku commented on src/detections/detection.rs
> +                                    "8003" | "8004" | "8006" | "8007" => {
channelはL81でPowerShellとなっていますが、マッチさせているeventIDがAppLockerのものになっています
以下のように変更していただくと正しいと思いますがいかがでしょうか。

```suggestion
                                    "4103" | "4104" => {
```

2021-04-29 14:26 UTC, hitenkoku commented on src/detections/detection.rs
> +                                    "4103" | "4104" => {
channelはL88でSysmonとなっていますが、マッチさせているeventIDがPowerShellのものになっています
以下のように変更していただくと正しいと思いますがいかがでしょうか。
```suggestion
                                    "1" | "7" => {
```

2021-04-29 14:26 UTC, hitenkoku commented on src/detections/detection.rs
> +                                    "1" | "7" => {
channelはL95でAppLockerとなっていますが、マッチさせているeventIDがSysmonのものになっています。
以下のように変更していただくと正しいと思います。

```suggestion
                                    "8003" | "8004" | "8006" | "8007" => {
```

2021-05-06 00:49 UTC, 7itoh commented on src/detections/detection.rs
> +                                    | "4625" | "4673" | "4674" | "4648" | "1102" => {
event_idの修正

2021-05-06 00:52 UTC, 7itoh reviewed
feature/detection

2021-05-06 00:52 UTC, 7itoh commented on src/detections/detection.rs
> +                                    "7030" | "7036" | "7045" | "7040" | "104" => {
event_idの修正

2021-05-06 00:52 UTC, 7itoh commented on src/detections/detection.rs
> +                                    "4103" | "4104" => {
event_idの修正

2021-05-06 00:52 UTC, 7itoh commented on src/detections/detection.rs
> +                                    "1" | "7" => {
event_idの修正

2021-05-06 00:52 UTC, 7itoh commented on src/detections/detection.rs
> +                                    "8003" | "8004" | "8006" | "8007" => {
event_idの修正

2021-05-06 00:52 UTC, 7itoh commented on src/detections/detection.rs
> +                                    "1" | "7" => {
46022cc により修正をしました。

2021-05-06 00:52 UTC, 7itoh commented on src/detections/detection.rs
> +                                    "4103" | "4104" => {
46022cc により修正をしました。

2021-05-06 00:53 UTC, 7itoh commented on src/detections/detection.rs
> +                                    "8003" | "8004" | "8006" | "8007" => {
46022cc により修正をしました。

2021-05-06 00:53 UTC, 7itoh commented on src/detections/detection.rs
> +                                    "7030" | "7036" | "7045" | "7040" | "104" => {
46022cc により修正をしました。

2021-05-06 00:53 UTC, 7itoh commented on src/detections/detection.rs
> +                                    "4688" | "4672" | "4720" | "4728" | "4732" | "4756"
46022cc により修正をしました。

2021-05-06 10:06 UTC, hitenkoku commented on src/detections/detection.rs
> +                                    "1" | "7" => {
確認しました。問題ないです。

2021-05-06 10:07 UTC, hitenkoku commented on src/detections/detection.rs
> +                                    "8003" | "8004" | "8006" | "8007" => {
確認しました。問題ないです

2021-05-06 10:07 UTC, hitenkoku commented on src/detections/detection.rs
> +                                    "4103" | "4104" => {
確認しました。問題ないです

2021-05-06 10:07 UTC, hitenkoku commented on src/detections/detection.rs
> +                                    "7030" | "7036" | "7045" | "7040" | "104" => {
確認しました。問題ないです

2021-05-06 10:07 UTC, hitenkoku commented on src/detections/detection.rs
> +                                    | "4625" | "4673" | "4674" | "4648" | "1102" => {
確認しました。問題ないです。

2021-05-06 10:08 UTC, hitenkoku approved these changes
確認しました。問題ないです

2021-05-06 12:22 UTC, ichiichi11 approved these changes
ok

2021-05-06 12:22 UTC, merged